//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_CommercePlatform
{
    public partial class Cart
    {
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        protected global::System.Web.UI.WebControls.Panel pnlCart;

        protected global::System.Web.UI.WebControls.GridView gvCart;

        protected global::System.Web.UI.WebControls.Label lblGrand;

        protected global::System.Web.UI.WebControls.Button btnCheckout;
    }
}
