//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_CommercePlatform
{
    public partial class Checkout
    {
        protected global::System.Web.UI.WebControls.GridView gvCheckout;

        protected global::System.Web.UI.WebControls.Label lblGrandTotal;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        protected global::System.Web.UI.WebControls.Button btnPlaceOrder;

        protected global::System.Web.UI.WebControls.Label lblMsg;
    }
}
