//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_CommercePlatform
{


    public partial class Home
    {

        /// <summary>
        /// btnBuy1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuy1;

        /// <summary>
        /// btnBuy2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuy2;

        /// <summary>
        /// btnBuy3 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuy3;

        /// <summary>
        /// btnBuy4 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuy4;

        /// <summary>
        /// btnBuy5 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuy5;

        /// <summary>
        /// btnBuy6 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuy6;

        /// <summary>
        /// btnBuy7 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuy7;

        /// <summary>
        /// btnBuy8 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuy8;
    }
}
