//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_CommercePlatform
{
    public partial class Site
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// phCart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phCart;

        /// <summary>
        /// phLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phLogin;

        /// <summary>
        /// phUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phUser;

        /// <summary>
        /// lblUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUser;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
